### ISSUE TITLE
Cannot create a an app within the current directory:

### ISSUE THREAD

**Issue by staceyd101** [asleepinglion/ng6-cli#10]
According to the docs the following should work
```
ng6 new app .
```

Instead the result is the path already exists. If you force the command the resulting name of the app is "."

**Comment by staceyd101** [comment]
This is still one small issue, it could probably considered an enhancement at this point but ...
```
First cd . to enter the project root.
```

**Comment by asleepinglion** [comment]
Good catch. I just need to pass the folder name instead of the command line argument when using the dot syntax in the new command.
